// <auto-generated />

using System.CodeDom.Compiler;
using System.Resources;
using System.Data.Entity.Migrations.Infrastructure;

namespace UBSWebApplication.Persistance.EF.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class PopulateDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopulateDatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201707021916375_PopulateDatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
